import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/meal_model.dart';
import '../services/ai_service.dart';

// 1. Bottom Navigation Tab Index
final navigationIndexProvider = StateProvider<int>((ref) => 0);

// 2. Holds the original meal currently selected for analysis / alternatives
final analyzedMealProvider = StateProvider<Meal?>((ref) => null);

// 3. Tracks whether the DeepSeek API is actively loading
final aiLoadingProvider = StateProvider<bool>((ref) => false);

// 4. Manages the list of alternative meals generated by the AI
final alternativesProvider = StateNotifierProvider<AlternativesNotifier, List<Meal>>((ref) {
  return AlternativesNotifier(ref);
});

class AlternativesNotifier extends StateNotifier<List<Meal>> {
  final Ref _ref;

  AlternativesNotifier(this._ref) : super([]);

  /// Fetches and converts raw AI alternatives into the `Meal` models expected by the UI
  Future<void> fetchAlternatives(Meal originalMeal) async {
    _ref.read(aiLoadingProvider.notifier).state = true;
    
    try {
      state = []; // Clear previous results immediately to show loading

      // Call the static method directly from your AiService
      final List<Map<String, dynamic>> rawAlternatives = 
          await AiService.generateAlternativeRecipes(
              originalMeal.name, 
              '${originalMeal.kcal}',
          );

      // Map the dynamic Maps from the API to strict integer-based Meal objects
      final List<Meal> mappedMeals = rawAlternatives.map((recipeMap) {
        return Meal(
          id: DateTime.now().millisecondsSinceEpoch.toString() + recipeMap['title'].hashCode.toString(),
          name: recipeMap['title'] ?? 'Alternative Recipe',
          time: recipeMap['prepTime'] ?? 'Ready to eat',
          kcal: _parseStringToInt(recipeMap['kcal']),
          protein: _parseStringToInt(recipeMap['protein']),
          carbs: _parseStringToInt(recipeMap['carbs']),
          fat: _parseStringToInt(recipeMap['fat']),
          icon: 'rice', // Default icon for recommendations
        );
      }).toList();

      state = mappedMeals;
    } catch (e) {
      print('Error mapping alternatives in provider: $e');
      state = [];
    } finally {
      _ref.read(aiLoadingProvider.notifier).state = false;
    }
  }

  /// Helper to extract numeric values from strings like "490 kcal" or "38g"
  int _parseStringToInt(dynamic value) {
    if (value == null) return 0;
    if (value is int) return value;
    if (value is double) return value.round();

    // Pull only the digits out of strings like "490 kcal" or "38g"
    final match = RegExp(r'\d+').firstMatch(value.toString());
    if (match != null) {
      return int.tryParse(match.group(0) ?? '0') ?? 0;
    }
    return 0;
  }

  void clear() {
    state = [];
  }
}