// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHWN4yNHuUfTOArxIcpU0tTcMK832d9_s',
    appId: '1:70457647569:web:d69f9036130c21625700f0',
    messagingSenderId: '70457647569',
    projectId: 'depi-final-project-a2760',
    authDomain: 'depi-final-project-a2760.firebaseapp.com',
    storageBucket: 'depi-final-project-a2760.firebasestorage.app',
    measurementId: 'G-DDLWG23EMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN9EamZ-ak9WACvSWLJDy14WI45s_21io',
    appId: '1:70457647569:android:54923ebe30a2253a5700f0',
    messagingSenderId: '70457647569',
    projectId: 'depi-final-project-a2760',
    storageBucket: 'depi-final-project-a2760.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHRd9atQ24Qjdo6zxThGwmsGz7jLstjcs',
    appId: '1:70457647569:ios:e53abcc3ebb8a31e5700f0',
    messagingSenderId: '70457647569',
    projectId: 'depi-final-project-a2760',
    storageBucket: 'depi-final-project-a2760.firebasestorage.app',
    iosClientId: '70457647569-uq2fegehuq2qf5ke0a378fujbkrne60r.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutriVision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHRd9atQ24Qjdo6zxThGwmsGz7jLstjcs',
    appId: '1:70457647569:ios:e53abcc3ebb8a31e5700f0',
    messagingSenderId: '70457647569',
    projectId: 'depi-final-project-a2760',
    storageBucket: 'depi-final-project-a2760.firebasestorage.app',
    iosClientId: '70457647569-uq2fegehuq2qf5ke0a378fujbkrne60r.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutriVision',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHWN4yNHuUfTOArxIcpU0tTcMK832d9_s',
    appId: '1:70457647569:web:311bb86f3721e9025700f0',
    messagingSenderId: '70457647569',
    projectId: 'depi-final-project-a2760',
    authDomain: 'depi-final-project-a2760.firebaseapp.com',
    storageBucket: 'depi-final-project-a2760.firebasestorage.app',
    measurementId: 'G-ERN86TLEQ7',
  );
}
